 @include('analytics/IMCIV1/html/graphsob')
@include('analytics/IMCIV1/html/Trained')
@include('analytics/IMCIV1/html/WorkingLocation')
@include('analytics/IMCIV1/html/Observation')
@include('analytics/IMCIV1/html/Classification')
@include('analytics/IMCIV1/html/ObservationB')
@include('analytics/IMCIV1/html/ClassificationB')
@include('analytics/IMCIV1/html/WeightTaken')
@include('analytics/IMCIV1/html/SpecialNeeds')  
@include('analytics/IMCIV1/html/sec3')
@include('analytics/IMCIV1/html/Consobsv')  
@include('analytics/IMCIV1/html/CertCriteriia')
@include('analytics/IMCIV1/html/Outcome')
@include('analytics/IMCIV1/html/ExitInterview')
@include('analytics/IMCIV1/html/Certification') 

 
